require('core.mappings')
require('core.plugins')
require('core.settings')
require('core.theme')

require('plugins.autosave')
require('plugins.cmp')
require('plugins.colorizer')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.neotree')
require('plugins.startup')
